const REFS={
  cdc:     {label:'CDC: Intimate Partner Violence',url:'https://www.cdc.gov/intimate-partner-violence/about/index.html'},
  lohmann: {label:'Lohmann et al., 2023',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10666508/'},
  stanley: {label:'Stanley et al., 2010',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3039217/'},
  owen:    {label:'Owen et al., 2013',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3656416/'},
  johnson: {label:'Johnson et al., 2021',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8915221/'},
  salvatore:{label:'Salvatore et al., 2011',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3060296/'},
  ha:      {label:'Ha et al., 2013',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3629130/'},
  haase:   {label:'Haase, 2023',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11210602/'},
  yilmaz:  {label:'Yılmaz et al., 2023',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10651749/'},
  dew:     {label:'Dew & Saxey, 2022',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9722948/'},
  peetz:   {label:'Peetz et al., 2023',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10632137/'},
  bogdan:  {label:'Bogdan et al., 2022 (meta-analysis)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9350520/'},
  vanderwal:{label:'van der Wal et al., 2023',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11143760/'},
  falconier:{label:'Falconier et al., 2015 (meta-analysis)',url:'https://pubmed.ncbi.nlm.nih.gov/26295276/'},
  rusu:    {label:'Rusu et al., 2020',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7145192/'},
  newkirk: {label:'Newkirk et al., 2017',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC5365149/'},
  aviv:    {label:'Aviv et al., 2024',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11761833/'},
  ciciolla:{label:'Ciciolla & Luthar, 2019',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8223758/'},
  mallory: {label:'Mallory, 2022 (meta-analysis)',url:'https://pubmed.ncbi.nlm.nih.gov/34968095/'},
  lebow:   {label:'Lebow et al., 2022',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10087549/'},
  megale:  {label:'Megale et al., 2021',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8127847/'},
  carroll: {label:'Carroll & Doherty, 2003',url:'https://scholarsarchive.byu.edu/facpub/4333/'},
  doss:    {label:'Doss et al., 2009',url:'https://pubmed.ncbi.nlm.nih.gov/19016573/'},
  mahoney: {label:'Mahoney et al., 2001',url:'https://pubmed.ncbi.nlm.nih.gov/10750665/'},
};

const Q=[
  {id:1,hw:true,refs:['stanley','owen'],
   en:{title:"Clear, mutual commitment",subtitle:"Choice, not inertia",
       thesis:"Readiness is stronger when commitment is a shared, deliberate decision rather than something a couple slides into. Research distinguishes dedication — an intrinsic desire to build a future together — from mere constraints that make leaving harder.",
       opts:{2:"We both clearly want this commitment and can articulate why. We are choosing it freely, not to fix major problems or relieve external pressure.",
             1:"We both lean toward commitment, but some reasons are vague, externally driven, or not fully clarified between us.",
             0:"One partner is significantly unsure, or commitment is being treated as a rescue plan, an exit from conflict, or a response to outside pressure."}},
   ko:{title:"진심으로 선택한 관계인가",subtitle:"흘러가다 보니가 아닌, 의도적 결정",
       thesis:"연구에 따르면 '함께 미래를 만들고 싶다'는 내면의 바람과, 그냥 헤어지기 어려워서 남아 있는 것은 전혀 다릅니다. 중요한 건 스스로 선택했는가입니다.",
       opts:{2:"두 사람 모두 이 관계를 원하고 왜 함께하고 싶은지 명확히 말할 수 있습니다. 문제를 해결하려거나 주변 압박 때문이 아니라, 진심으로 원해서 선택한 것입니다.",
             1:"두 사람 모두 함께하는 쪽으로 기울어 있지만, 이유가 다소 막연하거나 충분히 서로 확인되지 않은 부분이 있습니다.",
             0:"한 사람이 많이 망설이고 있거나, 이 관계가 갈등 해소나 외부 압박에 대한 반응으로 여겨지고 있습니다."}},
   detailed:[
     {refs:['stanley'],en:"I chose this relationship deliberately — not because I felt stuck, obligated, or afraid to leave.",ko:"나는 이 관계를 의도적으로 선택했습니다 — 갇혀 있거나, 의무감이나, 떠나기 두려워서가 아니라."},
     {refs:['stanley'],en:"I can clearly explain why I want to be with this person beyond surface-level reasons like attraction or comfort.",ko:"끌림이나 편안함 같은 표면적인 이유 외에, 왜 이 사람과 함께하고 싶은지 명확하게 설명할 수 있습니다."},
     {refs:['owen'],en:"My partner and I have explicitly discussed our future together — not just assumed we are on the same page.",ko:"파트너와 함께하는 미래에 대해 명확히 이야기 나눴습니다 — 그냥 같은 생각일 거라고 가정한 게 아닙니다."},
     {refs:['stanley'],en:"Neither of us is staying primarily because of practical constraints like a shared lease, finances, or social expectations.",ko:"우리 중 누구도 주로 현실적인 제약(공동 임대, 재정, 사회적 기대) 때문에 함께하는 게 아닙니다."},
     {refs:['owen'],en:"We are not in this relationship primarily to fix each other, escape a difficult period, or avoid being alone.",ko:"우리는 서로를 고치거나, 힘든 시기를 피하거나, 혼자 있기 싫어서 이 관계를 유지하는 게 아닙니다."},
     {refs:['stanley'],en:"Both of us are fully aware of the commitment we are making — no one is being rushed or pressured.",ko:"우리 둘 다 우리가 맺고 있는 관계의 의미를 충분히 알고 있습니다 — 누구도 서두르거나 강요받지 않습니다."},
     {refs:['owen'],en:"We have talked about what long-term commitment means to each of us — and our definitions are compatible.",ko:"장기적인 헌신이 각자에게 무엇을 의미하는지 이야기 나눴고, 우리의 정의가 서로 맞습니다."},
     {refs:['stanley'],en:"I feel confident this relationship is right for me — not just familiar, convenient, or the next expected step.",ko:"이 관계가 나에게 맞는다는 확신이 있습니다 — 단순히 익숙하거나, 편하거나, 다음 단계라서가 아니라."},
     {refs:['owen'],en:"External factors like family pressure, cultural expectations, or age are not the main reason we are moving forward.",ko:"외부 요인(가족 압박, 문화적 기대, 나이)이 우리가 함께 나아가는 주된 이유가 아닙니다."},
     {refs:['stanley'],en:"If I imagine our relationship 10 years from now, I can genuinely picture wanting to still be in it.",ko:"10년 후 우리의 관계를 상상할 때, 여전히 함께하고 싶다는 진심 어린 그림이 그려집니다."}
   ]},
  {id:2,hw:true,refs:['peetz','bogdan','vanderwal'],
   en:{title:"Alignment on the 'big rocks'",subtitle:"Children, finances, values, location, family, lifestyle",
       thesis:"High-stakes domains matter because they generate recurring, hard-to-compromise conflict. Financial disagreements predict later divorce; becoming parents typically lowers marital satisfaction even in good relationships; and value similarity supports both attraction and long-term functioning.",
       opts:{2:"We have discussed the major life domains and reached compatible answers or genuine, workable compromises — not just postponed decisions.",
             1:"We agree on some areas, but others are unclear, avoided, or built on idealized assumptions we haven't tested.",
             0:"There is a significant unresolved incompatibility in at least one major domain, or one or both of us avoids the conversation."}},
   ko:{title:"삶의 방향이 맞는가",subtitle:"자녀, 돈, 가치관, 거주지, 가족, 생활방식",
       thesis:"삶의 중요한 영역들이 맞지 않으면 타협하기 어려운 갈등이 반복됩니다. 돈 문제로 자주 싸우는 커플은 관계가 더 불안정하고, 아이를 낳은 뒤에는 좋은 관계도 만족도가 떨어지는 경우가 많습니다. 비슷한 가치관은 장기적 관계의 중요한 토대입니다.",
       opts:{2:"인생의 중요한 부분들을 이미 충분히 이야기했고, 방향이 맞거나 진심으로 합의할 수 있는 지점에 도달했습니다. 그냥 미뤄둔 게 아닙니다.",
             1:"일부는 맞지만, 아직 명확히 이야기 못 한 부분이 있거나, 막연하게 '어떻게 되겠지'라고 생각하는 영역이 있습니다.",
             0:"최소 하나의 중요한 영역에서 해결되지 않은 큰 차이가 있거나, 한 사람 이상이 그 대화 자체를 피하고 있습니다."}},
   detailed:[
     {refs:['doss'],en:"We have explicitly discussed whether we want children and reached a genuine agreement — not a silent hope that the other will eventually change their mind.",ko:"자녀를 원하는지에 대해 명확히 이야기 나눴고, 상대가 언젠가 마음을 바꾸길 속으로 기대하는 것이 아닌 진심으로 합의에 이르렀습니다."},
     {refs:['dew'],en:"We have discussed our core money values — spending vs. saving, risk tolerance, and financial priorities — and feel genuinely compatible.",ko:"소비 vs. 저축, 위험 감수 성향, 재정 우선순위 등 돈에 대한 핵심 가치관을 이야기 나눴고, 서로 진심으로 맞는다고 느낍니다."},
     {refs:['yilmaz','dew'],en:"We have fully disclosed debts, financial obligations, and financial history to each other — no significant financial surprises remain.",ko:"빚, 재정적 의무, 금융 이력을 서로 완전히 공개했으며, 아직 드러나지 않은 중요한 재정적 내용이 없습니다."},
     {refs:['mahoney'],en:"We are aligned not just on what we believe, but on how religion or spirituality will shape our daily home life and how we would raise children.",ko:"단순히 신념이 비슷한 것을 넘어, 종교나 영성이 일상적인 가정생활과 자녀 양육 방식에 어떤 역할을 할지에 대해서도 서로 맞닿아 있습니다."},
     {refs:['doss'],en:"If we plan to have children, we are aligned on core parenting approach — discipline style, educational priorities, and the role of extended family in raising children.",ko:"자녀를 계획한다면, 훈육 방식, 교육 우선순위, 양육에서 친인척의 역할에 대한 핵심 육아 철학이 서로 맞습니다."},
     {refs:['peetz'],en:"We are aligned on where we want to build our life long-term, and have discussed what happens if a career opportunity requires one of us to relocate.",ko:"장기적으로 어디서 살 것인지 방향이 맞고, 커리어로 인해 한 사람이 이사해야 하는 상황에 대해서도 이야기 나눴습니다."},
     {refs:['stanley'],en:"We have discussed and agree on how involved our families of origin will be — including time, emotional energy, and financial support expectations.",ko:"각자의 원가족이 우리 삶에 얼마나 관여할지를 이야기 나눴고, 시간, 정서적 에너지, 재정 지원 기대에 대해 합의했습니다."},
     {refs:['newkirk','ciciolla'],en:"We are compatible in how much of our lives we want dedicated to career versus relationship, family, and rest — neither feels held back or left behind.",ko:"커리어에 얼마나 삶을 쏟을지, 그리고 관계·가족·휴식과의 균형에 대해 서로 맞습니다. 어느 쪽도 억눌린다거나 뒤처진다는 느낌을 받지 않습니다."},
     {refs:['bogdan','vanderwal'],en:"We share enough foundational values — around fairness, gender roles, and what a good life looks like — that we feel we are building toward the same vision.",ko:"공정함, 성 역할, 좋은 삶이 무엇인지에 대한 근본적인 가치관을 충분히 공유하고 있어, 같은 방향을 향해 나아가고 있다고 느낍니다."},
     {refs:['vanderwal'],en:"Our daily lives are genuinely compatible — how we socialize, spend free time, approach health, and what a typical week looks like feels like something we both want.",ko:"교제 방식, 여가 활용, 건강에 대한 태도, 평범한 한 주의 모습 등 일상적인 삶이 진심으로 잘 맞습니다."}
   ]},
  {id:3,refs:['johnson','salvatore','ha'],
   en:{title:"Conflict skills & repair",subtitle:"How we fight and recover",
       thesis:"The issue is not whether you fight — conflict is normal — but whether it stays respectful and whether you can recover afterward. Lower negative communication consistently links to higher satisfaction, and repair ability predicts long-term stability.",
       opts:{2:"We can disagree without insults, contempt, humiliation, or character attacks. We apologize, de-escalate, and reconnect after conflict.",
             1:"We sometimes fight poorly or avoid conflict, but repair usually happens and we learn from difficult conversations.",
             0:"Conflict regularly becomes cruel, contemptuous, explosive, shut-down, or circular — with no real resolution or reconnection."}},
   ko:{title:"다툼과 화해",subtitle:"어떻게 싸우고, 어떻게 회복하는가",
       thesis:"갈등 자체는 나쁜 게 아닙니다. 중요한 건 싸울 때 서로를 존중하는지, 그리고 싸운 뒤 다시 회복할 수 있는지입니다. 회복 능력이 있는 커플이 장기적으로 더 안정적인 관계를 유지합니다.",
       opts:{2:"의견이 달라도 모욕이나 경멸, 인신공격 없이 대화할 수 있습니다. 싸우고 나면 사과하고, 감정을 가라앉히고, 관계를 회복합니다.",
             1:"때로 감정적으로 싸우거나 갈등을 피하기도 하지만, 대체로 화해가 이루어지고 어려운 대화에서 뭔가를 배웁니다.",
             0:"싸움이 자주 잔인해지거나, 경멸적이 되거나, 폭발하거나, 냉전으로 굳어버리고, 제대로 해결되지 않은 채 끝납니다."}},
   detailed:[
     {refs:['johnson'],en:"During arguments, I stay focused on the issue — I don't attack my partner's character or bring up unrelated grievances.",ko:"다툼 중에 나는 문제에 집중합니다 — 파트너의 성격을 공격하거나 관련 없는 불만을 꺼내지 않습니다."},
     {refs:['salvatore'],en:"Neither of us uses contempt — eye-rolling, mockery, or belittling — during conflict.",ko:"갈등 중에 우리 중 누구도 경멸(눈을 굴리거나, 비웃거나, 깎아내리는 것)을 사용하지 않습니다."},
     {refs:['johnson'],en:"When one of us gets overwhelmed, we can pause the conversation and return to it — rather than exploding or shutting down completely.",ko:"한쪽이 압도될 때, 대화를 잠시 멈추고 나중에 다시 돌아올 수 있습니다 — 폭발하거나 완전히 닫아버리는 대신."},
     {refs:['ha'],en:"We can both admit when we were wrong during or after a conflict.",ko:"갈등 중이나 후에 우리 둘 다 자신이 틀렸을 때 인정할 수 있습니다."},
     {refs:['salvatore'],en:"After a difficult argument, we are able to fully reconnect — there is no lingering coldness or resentment.",ko:"힘든 다툼 후에 우리는 완전히 다시 연결될 수 있습니다 — 남아 있는 냉기나 원망이 없습니다."},
     {refs:['johnson'],en:"We have a way of signaling to each other that a conversation is escalating and needs to slow down.",ko:"대화가 과열되어 속도를 늦춰야 할 때 서로에게 신호를 보내는 방법이 있습니다."},
     {refs:['salvatore'],en:"Neither of us stonewalls — goes completely silent or refuses to engage — as a regular response to conflict.",ko:"우리 중 누구도 갈등에 대한 일상적인 반응으로 냉전(완전히 침묵하거나 대화를 거부하는 것)을 사용하지 않습니다."},
     {refs:['ha'],en:"We can disagree about something without it becoming a threat to the relationship itself.",ko:"우리는 뭔가에 동의하지 않아도 그것이 관계 자체에 대한 위협이 되지 않습니다."},
     {refs:['johnson'],en:"We have repaired at least one significant conflict in a way that felt complete for both of us.",ko:"우리는 적어도 한 번의 중요한 갈등을 두 사람 모두에게 완전하게 느껴지는 방식으로 해결한 적이 있습니다."},
     {refs:['ha'],en:"Our arguments tend to end with some kind of resolution, understanding, or genuine repair — not just exhaustion.",ko:"우리의 다툼은 단순히 지쳐서 끝나는 게 아니라 어떤 해결, 이해, 또는 진정한 회복으로 끝나는 경향이 있습니다."}
   ]},
  {id:4,refs:['haase'],
   en:{title:"Emotion regulation under stress",subtitle:"Managing flooding in the moment",
       thesis:"When emotionally flooded, empathy and problem-solving both drop sharply. In couples, emotion regulation is a dyadic process — readiness means being able to pause, self-soothe, and return to conversation without causing lasting damage.",
       opts:{2:"When stressed or flooded, we can pause, self-soothe, and return to the conversation respectfully — even if it takes time.",
             1:"Stress sometimes triggers shutdown, defensiveness, or anger, but we can recover with effort and prevent lasting damage.",
             0:"Stress routinely leads to outbursts, cold withdrawal, disrespect, or ruptures we don't fully repair."}},
   ko:{title:"감정이 격해질 때",subtitle:"그 순간을 어떻게 넘기는가",
       thesis:"감정이 격해지면 공감 능력과 문제 해결 능력이 모두 떨어집니다. 둘 다 잠시 멈추고 마음을 가라앉혀 대화로 돌아올 수 있는지 — 이게 서로에게 상처를 남기지 않는 핵심입니다.",
       opts:{2:"감정이 격해지거나 스트레스를 받을 때, 잠깐 멈추고 스스로 진정한 뒤 다시 대화를 이어갈 수 있습니다.",
             1:"스트레스를 받으면 때로 말을 아예 멈추거나, 방어적이 되거나, 화를 내기도 합니다. 하지만 노력하면 회복할 수 있고, 서로에게 큰 상처를 남기지는 않습니다.",
             0:"스트레스가 쌓이면 폭발하거나, 냉담하게 벽을 쌓거나, 무례해지는 일이 반복되고, 그 상처가 제대로 아물지 않습니다."}},
   detailed:[
     {refs:['haase'],en:"I can recognize when I am becoming emotionally flooded and take steps to calm myself before responding.",ko:"내가 감정적으로 압도되고 있다는 것을 알아차리고, 반응하기 전에 스스로 진정하는 조치를 취할 수 있습니다."},
     {refs:['haase'],en:"When I am stressed, I do not take it out on my partner through irritability, criticism, or withdrawal.",ko:"스트레스를 받을 때, 짜증, 비판, 또는 거리두기를 통해 파트너에게 풀지 않습니다."},
     {refs:['haase'],en:"My partner and I can both express difficult emotions — anger, fear, sadness — without it becoming destructive.",ko:"파트너와 나 모두 힘든 감정(분노, 두려움, 슬픔)을 표현할 수 있으며, 그것이 파괴적이 되지 않습니다."},
     {refs:['haase'],en:"When I need time to calm down, I can ask for it clearly — and my partner respects that without feeling abandoned.",ko:"진정이 필요할 때, 명확하게 요청할 수 있고, 파트너는 버려진다고 느끼지 않고 그것을 존중합니다."},
     {refs:['haase'],en:"After calming down from an emotional spike, I can return to the conversation and engage productively.",ko:"감정적으로 고조된 후 진정되면, 대화로 돌아와 생산적으로 참여할 수 있습니다."},
     {refs:['haase'],en:"Neither of us uses emotional explosions — yelling, throwing things, slamming — as a pattern.",ko:"우리 중 누구도 감정 폭발(소리 지르기, 물건 던지기, 문 쾅 닫기)을 패턴으로 사용하지 않습니다."},
     {refs:['haase'],en:"I can stay emotionally regulated enough during hard conversations to actually hear what my partner is saying.",ko:"힘든 대화 중에도 감정적으로 충분히 조절하여 파트너가 말하는 것을 실제로 들을 수 있습니다."},
     {refs:['haase'],en:"Stress from outside our relationship — work, family, finances — does not routinely spill into how we treat each other.",ko:"외부 스트레스(직장, 가족, 재정)가 서로를 대하는 방식에 일상적으로 영향을 미치지 않습니다."},
     {refs:['haase'],en:"I am aware of my own emotional triggers and have shared them with my partner.",ko:"나의 감정적 촉발 요인을 알고 있으며 파트너와 공유했습니다."},
     {refs:['haase'],en:"We have a shared understanding of what each of us needs to regulate — and we support, not sabotage, each other in those moments.",ko:"각자가 감정을 조절하기 위해 필요한 것에 대한 공통된 이해가 있으며, 그 순간에 서로를 방해하지 않고 지지합니다."}
   ]},
  {id:5,hw:true,refs:['yilmaz','dew'],
   en:{title:"Trust & transparency",subtitle:"Especially money, contacts & boundaries",
       thesis:"Trust depends on predictable honesty and follow-through across all domains. It is foundational to stable relationships, and deception around finances or outside relationships is independently linked to poorer relationship functioning and lower satisfaction.",
       opts:{2:"No significant secrets. We are honest about money, boundaries, outside relationships, priorities, and loyalties. Trust feels stable and mutual.",
             1:"There are sensitive spots or past secrecy, but we are actively rebuilding trust with concrete, consistent follow-through.",
             0:"Repeated lying, hidden debt, covert contact, ongoing betrayal, or chronic suspicion is a current theme in the relationship."}},
   ko:{title:"신뢰와 솔직함",subtitle:"돈, 이성 관계, 경계선",
       thesis:"신뢰는 솔직함과 행동으로 쌓입니다. 특히 돈이나 이성 관계에 대한 거짓말은 관계 만족도를 낮추는 요인으로 관련 연구들에서 반복적으로 확인됩니다.",
       opts:{2:"중요한 비밀이 없습니다. 돈, 경계, 이성 관계, 가치 우선순위에 대해 솔직합니다. 서로를 믿는다는 느낌이 안정적입니다.",
             1:"과거에 비밀이나 거짓말로 신뢰가 약해진 적이 있지만, 구체적인 행동으로 신뢰를 다시 쌓아가는 중입니다.",
             0:"반복적인 거짓말, 숨겨진 빚, 몰래 이어진 연락, 지속적인 배신, 또는 끊이지 않는 의심이 지금 관계의 주된 문제입니다."}},
   detailed:[
     {refs:['yilmaz'],en:"I have no significant ongoing secrets from my partner about my life, finances, or outside relationships.",ko:"나의 삶, 재정, 또는 외부 관계에 대해 파트너로부터 숨기고 있는 중요한 비밀이 없습니다."},
     {refs:['dew'],en:"My partner follows through on what they say they will do — I can rely on their word.",ko:"파트너는 자신이 말한 것을 실행합니다 — 그들의 말을 믿을 수 있습니다."},
     {refs:['dew'],en:"I follow through on my own commitments consistently enough that my partner can rely on me.",ko:"나도 충분히 일관성 있게 약속을 이행하여 파트너가 나를 믿을 수 있습니다."},
     {refs:['yilmaz'],en:"There are no unresolved incidents of significant deception or betrayal that we haven't fully addressed.",ko:"충분히 다루지 않은 중요한 기만이나 배신 사건이 관계에 없습니다."},
     {refs:['yilmaz'],en:"I am honest with my partner even when the truth is uncomfortable or inconvenient.",ko:"불편하거나 어려운 경우에도 파트너에게 솔직합니다."},
     {refs:['dew'],en:"We both respect the boundaries we have agreed on regarding outside friendships and relationships.",ko:"우리 둘 다 외부 우정과 관계에 관해 합의한 경계를 존중합니다."},
     {refs:['yilmaz'],en:"I don't feel the need to check my partner's phone, messages, or whereabouts to feel secure.",ko:"안심하기 위해 파트너의 전화, 메시지, 또는 행방을 확인할 필요를 느끼지 않습니다."},
     {refs:['dew'],en:"When my partner raises a concern about trust, I take it seriously rather than dismissing or deflecting it.",ko:"파트너가 신뢰에 대한 우려를 제기할 때, 무시하거나 회피하지 않고 진지하게 받아들입니다."},
     {refs:['dew'],en:"My financial behavior — spending, debts, accounts — is fully transparent to my partner.",ko:"나의 재정적 행동(지출, 빚, 계좌)이 파트너에게 완전히 투명합니다."},
     {refs:['yilmaz'],en:"I feel genuinely safe being honest with my partner — I do not fear punishment or overreaction when I tell the truth.",ko:"파트너에게 솔직하게 말하는 것이 진심으로 안전하다고 느낍니다 — 진실을 말할 때 처벌이나 과잉반응을 두려워하지 않습니다."}
   ]},
  {id:6,refs:['falconier','rusu'],
   en:{title:"Team coping",subtitle:"Us versus the problem",
       thesis:"Couples do better when external stress becomes a shared task rather than evidence that the partner is the problem. Positive dyadic coping — especially supportive and coordinated coping — is strongly and consistently linked to relationship satisfaction.",
       opts:{2:"When life gets hard, we turn toward each other, coordinate, support, and solve together — rather than turning against each other.",
             1:"Under stress we sometimes become adversarial or withdraw, but we can reset and cooperate when we notice the pattern.",
             0:"Under stress, blame, scorekeeping, isolation, or mutual undermining becomes our default."}},
   ko:{title:"힘들 때 우리는 한 팀인가",subtitle:"문제 vs. 우리",
       thesis:"힘든 상황에서 상대를 문제로 보는 게 아니라 함께 문제를 푸는 동료가 될 때 관계가 훨씬 좋아집니다. 서로 의지하고 협력하는 커플이 관계 만족도도 높습니다.",
       opts:{2:"힘든 일이 생기면 서로를 의지하고, 함께 맞춰가며 지지하고 문제를 해결합니다.",
             1:"스트레스를 받으면 가끔 대립하거나 거리를 두기도 하지만, 패턴을 알아차리면 다시 협력해서 해결합니다.",
             0:"힘든 상황에서 비난하거나, 과거를 들먹이거나, 각자 고립되거나, 서로를 깎아내리는 것이 반복됩니다."}},
   detailed:[
     {refs:['falconier'],en:"When something stressful happens, our first instinct is to face it together rather than blaming or distancing.",ko:"스트레스가 생기면, 우리의 첫 번째 본능은 비난하거나 거리를 두는 게 아니라 함께 마주하는 것입니다."},
     {refs:['rusu'],en:"I genuinely support my partner's goals and wellbeing — even when it requires sacrifice from me.",ko:"나의 희생이 필요할 때도, 파트너의 목표와 행복을 진심으로 지지합니다."},
     {refs:['rusu'],en:"My partner genuinely supports my goals and wellbeing — I feel like they are in my corner.",ko:"파트너도 내 목표와 행복을 진심으로 지지합니다 — 그들이 내 편이라는 느낌이 있습니다."},
     {refs:['falconier'],en:"When we are under pressure, we coordinate rather than compete for resources like time, energy, and money.",ko:"압박을 받을 때, 우리는 자원(시간, 에너지, 돈)을 두고 경쟁하는 게 아니라 조율합니다."},
     {refs:['falconier'],en:"We can solve practical problems together — we divide responsibilities, communicate, and follow through.",ko:"우리는 함께 실질적인 문제를 해결할 수 있습니다 — 역할을 나누고, 소통하고, 실행합니다."},
     {refs:['rusu'],en:"Neither of us consistently makes the other feel alone during hard times.",ko:"힘든 시기에 우리 중 누구도 지속적으로 상대를 혼자라고 느끼게 하지 않습니다."},
     {refs:['rusu'],en:"I can express vulnerability — fear, sadness, uncertainty — to my partner and feel met with care, not judgment.",ko:"파트너에게 취약함(두려움, 슬픔, 불확실함)을 표현할 수 있으며, 판단이 아닌 돌봄으로 받아들여집니다."},
     {refs:['falconier'],en:"We celebrate each other's wins — neither of us consistently downplays the other's successes.",ko:"우리는 서로의 성공을 기뻐합니다 — 우리 중 누구도 상대의 성공을 지속적으로 폄하하지 않습니다."},
     {refs:['rusu'],en:"When one of us needs help, asking for it doesn't create conflict or resentment.",ko:"한쪽이 도움이 필요할 때, 도움을 요청하는 것이 갈등이나 원망을 만들지 않습니다."},
     {refs:['falconier'],en:"External stressors — financial, family, work — make us feel more united, not more divided.",ko:"외부 스트레스(재정, 가족, 직장)가 우리를 더 나누는 게 아니라 더 단결하게 만듭니다."}
   ]},
  {id:7,refs:['newkirk','aviv','ciciolla'],
   en:{title:"Fair division of labor & mental load",subtitle:"Visible and invisible work",
       thesis:"Fairness matters in both visible chores and the invisible planning work. Perceived unfairness in household labor is linked to more relationship conflict, and unequal cognitive labor is independently associated with poorer relationship functioning and worse mental health for the partner carrying it.",
       opts:{2:"Chores, admin, planning, remembering, and emotional labor feel fair enough to both of us — and we renegotiate when life changes.",
             1:"Some imbalance exists, but both partners acknowledge it and are actively working to rebalance.",
             0:"One partner consistently carries the visible or invisible load and feels unseen, resentful, or dismissed when raising it."}},
   ko:{title:"가사 노동과 정신적 노동의 공평한 분담",subtitle:"눈에 보이는 일, 눈에 보이지 않는 일",
       thesis:"집안일이 눈에 보이는 것과 보이지 않는 것을 가리지 않고 공평하게 나뉘어야 안정적인 관계를 유지할 수 있습니다. 챙기고, 기억하고, 계획하는 '보이지 않는 수고'도 포함됩니다. 이 부분에서 불공평하다고 느끼는 쪽이 관계에서 더 큰 부담을 느끼고, 정신 건강도 나빠진다는 연구가 있습니다.",
       opts:{2:"가사, 행정, 계획, 기억하기, 감정적 돌봄이 두 사람 모두에게 충분히 공평하게 느껴집니다. 상황이 바뀌면 다시 이야기해서 조정합니다.",
             1:"한쪽이 더 많이 하는 편이지만, 두 사람 모두 그 사실을 알고 있고 균형을 맞추려 노력하고 있습니다.",
             0:"한 사람이 보이는 일이든 보이지 않는 일이든 계속 혼자 짊어지고 있고, 그 얘기를 꺼내도 무시당하거나 억울함이 쌓여 있습니다."}},
   detailed:[
     {refs:['newkirk'],en:"Both of us contribute to household tasks — cooking, cleaning, errands — in a way that feels fair to both.",ko:"우리 둘 다 집안일(요리, 청소, 심부름)에 두 사람 모두에게 공평하다고 느껴지는 방식으로 기여합니다."},
     {refs:['ciciolla'],en:"The invisible mental work — remembering appointments, tracking needs, planning — is not carried primarily by one person.",ko:"보이지 않는 정신적 노동 — 약속 기억하기, 필요 파악하기, 계획하기 — 이 한 사람에게만 집중되지 않습니다."},
     {refs:['newkirk'],en:"When I raise an imbalance in our division of labor, my partner takes it seriously and works to address it.",ko:"내가 역할 분담의 불균형을 제기할 때, 파트너는 진지하게 받아들이고 해결하려 노력합니다."},
     {refs:['ciciolla'],en:"I am aware of how much invisible work my partner does — it doesn't go unseen or unacknowledged.",ko:"파트너가 하는 보이지 않는 일의 양을 알고 있습니다 — 눈에 보이지 않거나 인정받지 못하지 않습니다."},
     {refs:['aviv'],en:"We have explicitly discussed how we will divide responsibilities — it is not just assumed or left to default patterns.",ko:"역할을 어떻게 나눌지 명확하게 이야기 나눴습니다 — 그냥 가정하거나 기본 패턴에 맡기지 않았습니다."},
     {refs:['ciciolla'],en:"Neither of us carries the bulk of the emotional labor — managing feelings, keeping the peace, anticipating needs.",ko:"우리 중 누구도 감정 노동의 대부분을 혼자 짊어지지 않습니다 — 상대의 감정을 관리하고, 평화를 유지하고, 필요를 예상하는 일."},
     {refs:['aviv'],en:"When life circumstances change — new job, new baby, illness — we actively renegotiate our division of labor.",ko:"삶의 상황이 바뀔 때(새 직업, 아이, 아픔), 우리는 역할 분담을 능동적으로 재조정합니다."},
     {refs:['newkirk'],en:"Neither of us uses the other's lesser contribution in one area to score points or create obligation.",ko:"우리 중 누구도 한 영역에서 상대가 덜 기여한다는 사실을 점수를 매기거나 의무를 만드는 데 사용하지 않습니다."},
     {refs:['aviv'],en:"I genuinely appreciate the contributions my partner makes — I express this, not just think it.",ko:"파트너가 기여하는 것을 진심으로 감사하게 여깁니다 — 생각만 하는 게 아니라 표현합니다."},
     {refs:['ciciolla'],en:"We agree on what clean enough and organized enough looks like — standards mismatch doesn't create ongoing friction.",ko:"'충분히 깨끗한'과 '충분히 정리된'이 어떤 모습인지에 대해 동의합니다 — 기준 불일치가 지속적인 마찰을 만들지 않습니다."}
   ]},
  {id:8,refs:['lebow','megale','carroll'],
   en:{title:"Growth mindset & help-seeking",subtitle:"Openness to learning and support",
       thesis:"Relationship skills are learnable. Couple therapy and structured relationship education can meaningfully improve distress, communication, and mutual support — meaning openness to learning and help-seeking is a genuine resilience factor, not a sign of weakness.",
       opts:{2:"We believe relationship skills can be learned. We are open to feedback, self-improvement tools, and professional support if needed — before a crisis, not only during one.",
             1:"We are willing to try some self-help approaches, but support-seeking is inconsistent or meets resistance from one partner.",
             0:"One or both of us refuses feedback, consistently blames only the other, or rejects any tools or support outright."}},
   ko:{title:"함께 배우고 도움 받기",subtitle:"성장 의지와 도움 구하기",
       thesis:"관계 기술은 타고나는 게 아니라 배울 수 있습니다. 커플 상담이나 관계 교육은 소통과 갈등 해결 능력을 실질적으로 개선합니다. 도움을 구하는 것은 약함이 아니라 오히려 관계를 지키는 힘입니다.",
       opts:{2:"관계 기술은 노력으로 나아질 수 있다고 믿습니다. 위기가 터지기 전에도 피드백을 받아들이고, 도움이 된다면 상담도 기꺼이 받을 수 있습니다.",
             1:"뭔가 해보려는 의지는 있지만, 도움을 구하는 것이 일관적이지 않거나 한 사람이 저항하는 경우가 있습니다.",
             0:"한 사람 이상이 피드백을 거부하거나, 문제를 항상 상대 탓으로만 돌리거나, 어떤 도움도 받으려 하지 않습니다."}},
   detailed:[
     {refs:['lebow'],en:"I believe I can genuinely change and grow — that my relationship patterns are not fixed.",ko:"나는 진심으로 변하고 성장할 수 있다고 믿습니다 — 내 관계 패턴이 고정된 것이 아님을."},
     {refs:['carroll'],en:"When my partner gives me feedback about our relationship, I listen without becoming defensive or dismissive.",ko:"파트너가 관계에 대한 피드백을 줄 때, 방어적이 되거나 무시하지 않고 듣습니다."},
     {refs:['lebow'],en:"I take responsibility for my role in our relationship problems — I don't place all blame externally.",ko:"우리 관계 문제에서 내 역할에 대한 책임을 집니다 — 모든 것을 외부 탓으로 돌리지 않습니다."},
     {refs:['carroll'],en:"Both of us are willing to try new approaches when what we are doing is not working.",ko:"현재 하고 있는 것이 효과가 없을 때, 우리 둘 다 새로운 접근 방식을 시도할 의지가 있습니다."},
     {refs:['lebow'],en:"We would both be open to couples therapy or counseling — not just in a crisis but as a proactive tool.",ko:"우리 둘 다 커플 상담에 열려 있습니다 — 위기 때만이 아니라 선제적인 도구로서."},
     {refs:['megale'],en:"We have used at least one resource — book, podcast, course, or therapist — to intentionally improve our relationship.",ko:"관계를 의도적으로 개선하기 위해 적어도 하나의 자원(책, 팟캐스트, 강좌, 상담사)을 사용한 적이 있습니다."},
     {refs:['carroll'],en:"Neither of us treats asking for outside help as a sign of weakness or failure.",ko:"우리 중 누구도 외부 도움을 구하는 것을 약점이나 실패의 징조로 여기지 않습니다."},
     {refs:['lebow'],en:"I regularly reflect on my own behavior in the relationship — not just what my partner does wrong.",ko:"관계에서 파트너가 잘못하는 것만이 아니라, 내 자신의 행동을 정기적으로 돌아봅니다."},
     {refs:['megale'],en:"We can have honest meta-conversations — talking about how we communicate, not just what we are communicating about.",ko:"어떻게 소통하는지에 대해 — 무엇을 소통하는지뿐만 아니라 — 솔직한 메타 대화를 나눌 수 있습니다."},
     {refs:['carroll'],en:"Growth and change in ourselves individually is encouraged — not seen as a threat to the relationship.",ko:"개인적으로 성장하고 변화하는 것이 장려되며, 관계에 대한 위협으로 보이지 않습니다."}
   ]},
  {id:9,refs:['mallory'],
   en:{title:"Sexual communication & intimacy",subtitle:"Safety and openness to talk",
       thesis:"Sexual readiness is less about 'perfect chemistry' and more about the ability to talk safely about consent, desire differences, pain, contraception, health, and preferences. Better sexual communication is reliably associated with both relationship and sexual satisfaction across multiple meta-analyses.",
       opts:{2:"We can talk openly and respectfully about sex — including consent, desire differences, boundaries, contraception, pain, and preferences.",
             1:"The topic is awkward or avoided at times, but we can communicate when it genuinely matters.",
             0:"Sex involves fear, shame, coercion, consistently ignored pain, or an inability to discuss it safely."}},
   ko:{title:"성적 소통과 친밀감",subtitle:"편하게 이야기할 수 있는가",
       thesis:"오래가는 관계에서 중요한 것은 '완벽한 궁합'이 아니라 동의, 욕구 차이, 불편함, 피임, 건강, 성적 선호에 대해 편하게 이야기할 수 있는가입니다. 성적 소통이 잘 되는 커플이 관계 만족도와 성생활 만족도 모두 높다는 연구 결과가 일관되게 나옵니다.",
       opts:{2:"동의, 욕구 차이, 경계, 피임, 불편함, 선호 등 성에 관한 이야기를 편하고 솔직하게 나눌 수 있습니다.",
             1:"이 주제로 대화할 때 어색하거나 피하게 될 때도 있지만, 정말 필요할 때는 이야기할 수 있습니다.",
             0:"성관계에 두려움, 수치심, 강요, 무시되는 불편함이 있거나, 이 주제를 안전하게 꺼낼 수 없습니다."}},
   detailed:[
     {refs:['mallory'],en:"We can discuss what we each want and don't want sexually — without shame, awkwardness, or conflict.",ko:"수치심, 어색함, 갈등 없이 각자 성적으로 원하는 것과 원하지 않는 것에 대해 이야기 나눌 수 있습니다."},
     {refs:['mallory'],en:"Both partners' consent is always clear, enthusiastic, and freely given — never assumed or pressured.",ko:"두 파트너의 동의는 항상 명확하고, 자발적이며, 자유롭게 주어집니다 — 가정되거나 강요되지 않습니다."},
     {refs:['mallory'],en:"When one of us says no or not now, it is always respected without guilt-tripping or sulking.",ko:"한쪽이 거절하거나 지금은 아니라고 할 때, 죄책감을 주거나 투정 없이 항상 존중됩니다."},
     {refs:['mallory'],en:"We have talked about differences in desire or frequency — it hasn't been left as an unspoken tension.",ko:"욕구나 빈도의 차이에 대해 이야기 나눴습니다 — 말하지 않은 긴장으로 남겨두지 않았습니다."},
     {refs:['mallory'],en:"Physical pain or discomfort during intimacy — if present — is acknowledged and addressed, not ignored.",ko:"친밀감 중 신체적 통증이나 불편함이 있다면 — 무시되지 않고 인정되고 다뤄집니다."},
     {refs:['mallory'],en:"We have discussed contraception and sexual health openly and reached a shared approach.",ko:"피임과 성 건강에 대해 솔직하게 이야기 나눴고 공통된 접근 방식에 이르렀습니다."},
     {refs:['mallory'],en:"Intimacy in our relationship doesn't feel like a source of anxiety, obligation, or avoidance for either of us.",ko:"우리 관계에서 친밀감은 우리 중 누구에게도 불안, 의무감, 또는 회피의 원천처럼 느껴지지 않습니다."},
     {refs:['mallory'],en:"We are able to talk about what is working and what is not in our physical relationship — not just endure it silently.",ko:"우리의 신체적 관계에서 무엇이 효과적이고 그렇지 않은지 이야기 나눌 수 있습니다 — 그냥 조용히 참지 않고."},
     {refs:['mallory'],en:"Neither partner consistently initiates while the other consistently refuses — the dynamic is not stuck in a fixed pattern.",ko:"한 파트너가 지속적으로 시작하고 다른 쪽이 지속적으로 거절하지 않습니다 — 고정된 패턴에 갇혀 있지 않습니다."},
     {refs:['mallory'],en:"Emotional and physical intimacy feel connected in our relationship — we don't consistently have one without the other.",ko:"우리 관계에서 정서적 친밀감과 신체적 친밀감이 연결되어 있습니다 — 하나 없이 다른 하나만 지속적으로 있지 않습니다."}
   ]},
  {id:10,gate:true,hw:true,refs:['cdc','lohmann'],
   en:{title:"Safety, respect & autonomy",subtitle:"The foundation everything else rests on",
       thesis:"Safety underpins every other item on this list. Intimate partner violence includes psychological aggression, coercive control, stalking, sexual coercion, and physical violence — all associated with PTSD, depression, and long-term trauma.",
       opts:{2:"We consistently treat each other with respect. No intimidation, threats, coercion, surveillance, sexual pressure, or physical aggression. Boundaries and 'no' are always honored.",
             1:"Mostly respectful, with occasional hurtful escalations or boundary slips that are acknowledged, repaired, and becoming less frequent.",
             0:"Any current pattern of fear, control, threats, sexual pressure, physical aggression, or coercion — regardless of how infrequent."}},
   ko:{title:"안전, 존중 & 자율성",subtitle:"다른 모든 것의 토대",
       thesis:"안전은 이 목록의 다른 모든 항목의 토대입니다. 심리적 위협, 강압, 스토킹, 성적 강요, 신체적 폭력은 데이트 폭력에 해당하며, PTSD, 우울증, 오랜 트라우마로 이어질 수 있습니다.",
       opts:{2:"서로를 한결같이 존중합니다. 협박이나 감시, 성적 강요, 폭력은 전혀 없고, 상대가 싫다고 할 때 그 말이 언제나 받아들여집니다.",
             1:"대체로 서로를 존중하지만, 가끔 선을 넘거나 상처를 주는 일이 있습니다. 다만 그럴 때마다 인정하고 회복하며, 점점 줄어들고 있습니다.",
             0:"두려움, 통제, 위협, 성적 강요, 신체적 폭력 중 하나라도 빈도와 상관없이 지금 반복되고 있습니다."}},
   detailed:[
     {refs:['cdc'],en:"I never feel afraid of my partner's reactions — I can speak freely without fearing punishment or retaliation.",ko:"파트너의 반응이 두렵지 않습니다 — 처벌이나 보복을 두려워하지 않고 자유롭게 말할 수 있습니다."},
     {refs:['lohmann'],en:"My partner respects my boundaries — when I say no to anything, plans, physical contact, or topics, it is honored.",ko:"파트너는 나의 경계를 존중합니다 — 내가 무엇이든 거절할 때(계획, 신체적 접촉, 주제), 그것이 존중됩니다."},
     {refs:['cdc'],en:"Neither of us monitors or controls the other's phone, money, friendships, or movements.",ko:"우리 중 누구도 상대의 전화, 돈, 우정, 또는 행동을 감시하거나 통제하지 않습니다."},
     {refs:['lohmann'],en:"I feel free to spend time with friends and family independently — without guilt, interrogation, or punishment.",ko:"죄책감, 심문, 또는 처벌 없이 친구 및 가족과 독립적으로 시간을 보낼 자유를 느낍니다."},
     {refs:['cdc'],en:"There is no physical aggression in our relationship — no hitting, pushing, grabbing, or throwing, no matter how rarely.",ko:"우리 관계에서 신체적 공격이 없습니다 — 아무리 드물더라도, 때리기, 밀기, 잡기, 던지기가 없습니다."},
     {refs:['lohmann'],en:"There is no pattern of threats — including threats to leave, to hurt themselves, or to expose private information.",ko:"위협의 패턴이 없습니다 — 떠나겠다는 위협, 자해 위협, 또는 사적 정보 노출 위협을 포함하여."},
     {refs:['cdc'],en:"Disagreements in our relationship do not involve humiliation, name-calling, or deliberate cruelty.",ko:"우리 관계의 불일치가 굴욕, 욕설, 또는 의도적인 잔인함을 수반하지 않습니다."},
     {refs:['lohmann'],en:"My autonomy is respected — I make my own decisions about my body, career, friendships, and beliefs without requiring my partner's approval.",ko:"나의 자율성이 존중됩니다 — 파트너의 승인 없이 신체, 직업, 우정, 신념에 관한 나 자신의 결정을 내립니다."},
     {refs:['cdc'],en:"I feel like an equal in this relationship — not subordinate, managed, or dependent.",ko:"이 관계에서 평등하다고 느낍니다 — 종속적이거나, 관리되거나, 의존적이지 않습니다."},
     {refs:['lohmann'],en:"When I imagine bringing up any concern to my partner, I feel safe — not braced for escalation, rage, or shutdown.",ko:"파트너에게 어떤 우려든 제기하는 것을 상상할 때, 안전하다고 느낍니다 — 에스컬레이션, 분노, 또는 차단을 각오하지 않아도 됩니다."}
   ]}
];

const SC={2:{cls:'b2',selCls:'sel-2'},1:{cls:'b1',selCls:'sel-1'},0:{cls:'b0',selCls:'sel-0'}};
const PC={A:'#3B7A7C',B:'#6A55A0'};
